CREATE DATABASE LIVRARIA;

USE LIVRARIA;

CREATE TABLE LIVRO(
    NOME_LIVRO VARCHAR(60),
    NOME_AUTOR VARCHAR(60),
    SEXO_AUTOR CHAR(1),
    NUMERO_PAGINAS INT(6),
    NOME_EDITORA VARCHAR(60),
    VALOR_LIVRO FLOAT(6, 2),
    UF_EDITORA CHAR(2),
    ANO_PUBLICACAO INT(4)
);

INSERT INTO LIVRO(NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUMERO_PAGINAS, NOME_EDITORA, VALOR_LIVRO, 
UF_EDITORA, ANO_PUBLICACAO) VALUES('CAVALEIRO REAL', 'ANA CLAUDIA', 'F', 465, 'ATLAS', 49.9, 'RJ', 2009);

INSERT INTO LIVRO(NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUMERO_PAGINAS, NOME_EDITORA, VALOR_LIVRO, 
UF_EDITORA, ANO_PUBLICACAO) VALUES('SQL Para Leigos', 'João Nunes', 'M', 450, 'Addison', 98, 'SP', 2018);



INSERT INTO LIVRO(NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUMERO_PAGINAS, NOME_EDITORA, VALOR_LIVRO, 
UF_EDITORA, ANO_PUBLICACAO) VALUES('Receitas Caseiras', 'Celia Tavares', 'F', 210, 'Atlas', 45, 'RJ', 2008);

INSERT INTO LIVRO(NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUMERO_PAGINAS, NOME_EDITORA, VALOR_LIVRO, 
UF_EDITORA, ANO_PUBLICACAO) VALUES('Pessoas Efetivas', 'Eduardo Santos', 'M', 390, 'Beta', 78.99, 'RJ', 2018);

INSERT INTO LIVRO(NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUMERO_PAGINAS, NOME_EDITORA, VALOR_LIVRO, 
UF_EDITORA, ANO_PUBLICACAO) VALUES('Hábitos Saudáveis', 'Eduardo Santos', 'M', 630, 'Beta', 150.98, 'RJ', 2019);

INSERT INTO LIVRO(NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUMERO_PAGINAS, NOME_EDITORA, VALOR_LIVRO, 
UF_EDITORA, ANO_PUBLICACAO) VALUES('A Casa Marrom', 'Hermes Macedo', 'M', 250, 'Bubba', 60, 'MG', 2016);

INSERT INTO LIVRO(NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUMERO_PAGINAS, NOME_EDITORA, VALOR_LIVRO, 
UF_EDITORA, ANO_PUBLICACAO) VALUES('Estacio Querido', 'Geraldo Francisco', 'M', 310, 'Insignia', 100, 'ES', 2015);

INSERT INTO LIVRO(NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUMERO_PAGINAS, NOME_EDITORA, VALOR_LIVRO, 
UF_EDITORA, ANO_PUBLICACAO) VALUES('Pra Sempre Amigas', 'Leda Silva', 'F', 510, 'Insignia', 78.98, 'ES', 2011);

INSERT INTO LIVRO(NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUMERO_PAGINAS, NOME_EDITORA, VALOR_LIVRO, 
UF_EDITORA, ANO_PUBLICACAO) VALUES('Copas Inesquecíveis', 'Marco Alcantara', 'M', 200, 'Larson', 130.98, 'RS', 2018);

INSERT INTO LIVRO(NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUMERO_PAGINAS, NOME_EDITORA, VALOR_LIVRO, 
UF_EDITORA, ANO_PUBLICACAO) VALUES('O Poder Da Mente', 'Clara Mafra', 'F', 120, 'Continental', 56.58, 'SP', 2017);

/*Querys*/

/*Trazer Todos os dados*/

SELECT * FROM LIVRO;

/*Trazer o Nome do livro e o nome da editora*/

SELECT NOME_LIVRO AS LIVRO, NOME_EDITORA AS EDITORA FROM LIVRO;

/*Trazer o Nome do livro e a UF dos Livros publicados por autores do sexo Masculino*/

SELECT NOME_LIVRO AS LIVRO, UF_EDITORA AS ESTADO_DA_EDITORA FROM LIVRO
WHERE SEXO_AUTOR = 'M';

/*TRAZER O NOME DO LIVRO E O NÚMERO DE PÁGINAS DOS LIVROS PUBLICADOS POR AUTORES DO SEXO FEMININO*/

SELECT NOME_LIVRO AS LIVRO, NUMERO_PAGINAS AS PAGINAS FROM LIVRO
WHERE SEXO_AUTOR = 'F';

/*TRAZER OS VALORES DOS LIVROS DAS EDITORAS DE SÃO PAULO*/

SELECT VALOR_LIVRO AS VALOR FROM LIVRO
WHERE UF_EDITORA = 'SP';

/*TRAZER OS DADOS DOS AUTORES DO SEXO MASCULINO QUE TIVERAM LIVORS PUBLICADOS POR SAO PAULO OU RIO DE JANEIRO*/

SELECT NOME_AUTOR AS NOME, SEXO_AUTOR AS SEXO FROM LIVRO
WHERE SEXO_AUTOR = 'M' AND (UF_EDITORA = 'SP' OR UF_EDITORA = 'RJ');